### ISSUE TITLE
汎用データベースの 編集 ＞ 表示方法 の設定内容が正しく表示されない件

### ISSUE THREAD

**Issue by nagasheep** [netcommons/NetCommons2#1]
こんにちわ。
オープンソース・ワークショップの永原です。

汎用データベースの 編集 ＞ 表示方法 で設定した内容が、正しく画面に反映されません。
データベース上は保存されているみたいなのですが、「表示方法」タブでは表示件数10件、表示順がカスタマイズ順になってしまいます。

ということで、テスト込みで書き込みしてみました。
こんな感じでよかったかな。

**Comment by nagasheep** [comment]
永原です。

Validator_MultidatabaseView.class.php の 54行目がおかしいことはわかるのですが、2.3.3.0 から 2.4.0.0 へのバージョンアップで修正された部分のようです。

その修正の意図が読み取れないので、その辺のヒントはないかなぁ。

**Comment by kteraguchi** [comment]
2.4.0.0での修正バグと思われます。
編集のアクション名を「OR」でみていたので、まとめたのだと思いますが、表示方法変更画面も含まれるようになってしまった感じです。

修正ありがとうございます。
