### ISSUE TITLE
日誌のタイトルが改行されない件

### ISSUE THREAD

**Issue by nagasheep** [netcommons/NetCommons2#16]
こんにちわ。
オープンソース・ワークショップの永原です。

日誌のタイトルが改行されないため、画面の幅が伸びてしまう。という件があったと思います。

改行させない、ということにあまり意味はないのかなと思うので、改行できるようにしたいと思います。

**Comment by kteraguchi** [comment]
たまたま、ハンドル名が長いテストユーザーで、動作確認したところタイトルの幅が、極端に狭くなっちゃいました。
ブロックの幅指定も影響してるせいだと思います。
今回リリースに含めますが、改行が嫌な人は修正箇所を修正しないようにアナウンスする事にします。
（新着も同様です。）

**Comment by nagasheep** [comment]
永原です。
失礼！ハンドル名もwhite-space: nowrap 指定がありました。
そっちも外さなきゃいけなかったですね。
ハンドルが改行するのも、ちょっと微妙な感じもありますが、仕方ない部分かな。
すぐした方が良ければ言ってください！

**Comment by kteraguchi** [comment]
おおぉぉ。
そうか！ハンドル名もwhite-space: nowrap とっちゃえば良い話ですね。
こっちでやっときます！

**Comment by nagasheep** [comment]
ありがとうございます！
