### ISSUE TITLE
施設予約 日表示での予約時に些細な表示バグ

### ISSUE THREAD

**Issue by akagane99** [netcommons/NetCommons2#18]
こんにちは。
オープンソースワークショップの牟田口です。

施設予約モジュールで些細な表示バグを見つけたので、報告します。
後程パッチをアップします。

--- 再現

・施設予約 日表示にする。
・カテゴリ選択する。
・予約登録時、「-- 施設の絞り込み --」が選択したカテゴリになってない。
・「施設」はカテゴリで絞られたものが表示されている。

--- 対応

・予約登録時、「-- 施設の絞り込み --」を選択したカテゴリにする。

以上です。

**Comment by akagane99** [comment]
html　の diffずれのため、再アップしましたが、改善せず。

・C:\Program Files (x86)\Git\etc\gitconfig
[core]
autoCRLF = false
の確認。（既に設定済みだった）

今のところ、お手上げです。
他に改善方法をご存知の方がいらっしゃいましたら、ご教授頂けると助かります。

**Comment by nagasheep** [comment]
ホントに改行の問題だったかな？（とちょっと気になった）
公開バージョンの2.4.0.0 ソースは見てみた？

**Comment by akagane99** [comment]
htmlのdiffが正しくできない件、解決しました。

--- ポイント　gitconfigが２つあった。

・C:\Program Files (x86)\Git\etc\gitconfig
・%USERPROFILE%\AppData\Local\GitHub\PortableGit_どーたらこーたら\etc\gitconfig

このgitconfig内のパラメータを以下に変更

 [core]
 autoCRLF = false

histroy汚してすんません。
以上です。

**Comment by nagasheep** [comment]
解決して良かったねー。ということで、「いいね！」
