### ISSUE TITLE
文書型宣言の前の空行を削除

### ISSUE THREAD

**Issue by nagasheep** [netcommons/NetCommons2#42]
komuna さんの以下のPull Requests をマージしました。
#37

**Comment by kteraguchi** [comment]
リリースに向けてマージ中です。
当件（#42）、および、komuna さんの以下のPull Requests（#37）  については、前回リリース時に入れた修正です。

これは、WindowsのMHTMLにおけるセキュリティ問題があり、それに対応した修正になります。
根本的な解決としては、Windowsをアップデートすることになるのですが、
リリース前のソースに対して、セキュリティスキャンソフトを実行することにしており、
その際、スキャンソフトに引っかかってしまうため、見た目が悪くなるのですが、いたしかたなく入れた修正です。

ソースの気持ち悪さは仰るとおりですが、マージする前に戻そうと考えております。
とりあえず、他の修正のマージを行って、最後に戻します。
何かありましたら、コメント頂ければと思います。

**Comment by komuna** [comment]
おお，そういうことでしたか。全然知らなくてすみません。
Windows の MHTML に関する脆弱性に関連してセキュリティーソフトが文書型宣言で始まるファイルを誤検知しちゃう，という理解でよろしいでしょうか？
後学のためどんなソフトか教えていただけませんか。（自分の他の仕事に関係するかも？と気になるので）

**Comment by kteraguchi** [comment]
コメントありがとうございます。

　> 全然知らなくてすみません。
いえ、いえ。こういった事例から、少しずつ情報が共有していければ良いかなと思っています。

　> セキュリティーソフトが文書型宣言で始まるファイルを誤検知しちゃう
だいたい、そんな感じです。
詳細については、当内容が公開されているため、申し上げられませんが、カンファレンスや、セミナー等で、
お会いできれば、口頭で言えることもあるかと思います。

　> どんなソフトか教えていただけませんか。
すみません。これは非公開としております。
MHTMLの脆弱性を引っかけてくれますから、かなり優秀？と思っています。

公式サイトの返信を含め、ご協力感謝しています。
引き続きよろしくお願いいたします。

**Comment by komuna** [comment]
分かりました。
