### ISSUE TITLE
日誌の投稿者の「by:」のあとを空ける

### ISSUE THREAD

**Issue by komuna** [netcommons/NetCommons2#43]
日誌の投稿者名が「by:norico」のように表示されますが，コロンのあとを空けないのは英語の正書法として変です。
もっと言えば，コロンがあること自体変です。

よって，「by:」を「by 」もしくは「by: 」にすることを提案します。

修正箇所は
webapp/modules/journal/language/{japanese,english}/main.ini
（計2ファイル）の journal_from の値です。

**Comment by nagasheep** [comment]
こんにちわ。永原です。

英語が詳しくなくて、すみません（^^）
何か、この文法はおかしいよと確認できるようなものってないですかねぇ。
プログラム言語に対するリファレンスマニュアルやインターネットプロトコルに対するRFCみたいなものを想像しています。

**Comment by komuna** [comment]
まず，「コロンを付けるなら後ろにスペースを入れる」のほうですが，これは文法の問題というより表記ルールです。改めて問われると根拠となる文書を示すのは難しいですね。見つけられませんでした。Oxford Guide to Style (2002) や The Chicago Manual of Style, 14th ed. (1993) とかも見てみましたが，記述は無いようでした。ただし，これらにで出てくる例文はすべてコロンのあとを空けています。
「カンマのあとは空ける」と同じことなのですが。
なお，時刻表示の「18:50」，比の「2:3」などは話が別です。

それから，そもそも「by」のあとにコロンを付けるかどうか。付けても間違いではないでしょうが，余計です。
こちらも RFC 的な文書は見つけられませんでした。
