### ISSUE TITLE
携帯のパスワード入力欄について

### ISSUE THREAD

**Issue by nagasheep** [netcommons/NetCommons2#5]
こんにちわ。
オープンソース・ワークショップの永原です。

携帯のパスワード入力欄ですが、input type="password" ですよね。
携帯では、入力欄がマスクされるのって、使いにくいと思うので、携帯のパスワードは通常のテキストの方が良いかなと思うのですが、いかがでしょうか。
（テンキー入力なので）

**Comment by RikaFujiwara** [comment]
これは２派にわかれますよね
面倒だからテキストにしようという派とパスワードなのに丸見えにしてどうすんだの派。
要はユーザーターゲットとおよびログイン後のコンテンツの秘匿具合によってここのオープン度が変わるのかなと思います。
自分としてはpasswdのほうがいいのではないかと思っています。
携帯の機種によっても入力の最後の一文字がちゃんと残るような気づかいをしているものもありますし。

**Comment by akagane99** [comment]
自分もinput type="password"に１票です。
【理由】
・type="password"ならリダイレクトした時に、自動的に消えてくれる。
・上記の理由から type="password" -> type="text"  に変更するとほんの少しセキュリティが下がります。

**Comment by RikaFujiwara** [comment]
あと、textタイプの入力エリアで入力したものは、携帯の学習機能で「入力候補」にｎ入れられる可能性がありますね。
他人が触るような場面で、入力候補にパスワードが上がってきたら、、、やはりpasswdのほうが望ましいのでは。

**Comment by nagasheep** [comment]
永原です。
ガラケーによって、パスワード欄の見え方が違うんですね。勉強になりました。

特に、以下の内容でなるほど！と思いました。

＞ あと、textタイプの入力エリアで入力したものは、携帯の学習機能で「入力候補」に入れられる可能性がありますね。

これを考えると、password のままにすべき。かなと思いました。

ということで、このスレッドはClose にしたいと思います。
（自分で立てた質問スレッドなので、自分でClose してもOK ですよね）

以上、コメント頂いた方、貴重なご意見ありがとうございました。
