### ISSUE TITLE
アンケートで質問の編集リンクが効かないことがある

### ISSUE THREAD

**Issue by kteraguchi** [netcommons/NetCommons2#68]
再現性に欠けるため、原因の特定が難しかったが、
解説に画像があると、再現する頻度UP！

質問詳細画面にある
javascriptのfocus処理があやしい。

小テストも同様と思われる。

**Comment by akagane99** [comment]
以下で再現できました。

--- 前提
ブラウザを開いてから、wysiwygを1度も開いてない。

--- 手順
アンケート作成後、質問の編集の後、「解説がある質問」の編集リンクを押しても編集画面が開かなかった。

--- 原因
wysiwygのjsクラス、compTextareaをnewするタイミングで、まだクラスの準備が途中なのに、wysiwygにフォーカスを当てようとしてエラーになっていた。

修正ソース、この後アップします。
