### ISSUE TITLE
Github のソースに以下のフォルダがありません。

### ISSUE THREAD

**Issue by nagasheep** [netcommons/NetCommons2#8]
オープンソース・ワークショップ 永原です。

Github のソースに以下のフォルダがありません。

/webapp/templates_c
/webapp/uploads

なんか意図があって、ないのかな？
それとも、空のフォルダは作れないとか？

インストール時にチェックがかかるので。

以上、気になったので確認です。

**Comment by akagane99** [comment]
subversionなどと同じく、空フォルダは作れないですね。
なので、空フォルダ作りたいときは、そのフォルダに .gitkeep　という名前の空ファイルを作って維持する方法を使ってます。
よそでも見かけますね。

参考まで。

**Comment by nagasheep** [comment]
永原です。
なるほど。そうなのね。
特に問題はないように思えます。
しばらく放置して、反対がなければそれで良いのかな。
